# Generated by Django 3.2.9 on 2021-11-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('order_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order_detail')),
            ],
        ),
    ]
