# Generated by Django 3.2.9 on 2021-11-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField(default=0.0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('img_path', models.CharField(max_length=512)),
            ],
        ),
    ]
