# Generated by Django 3.2.9 on 2021-11-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
